### ISSUE TITLE
Expand on Service Locator explanation for Lagom

### ISSUE THREAD

**Issue by longmuir** [lightbend/lightbend-orchestration-docs#27]
https://developer.lightbend.com/docs/reactive-platform-tooling/latest/project-configuration.html

It's not clear what functionality adding in the LagomServiceLocatorComponents or ServiceLocatorModule is providing unless you start digging into source code, understand what Lagom's service location is, and understand how Kubernetes DNS SRV works (not a safe assumption) and start putting it all together. There will also be questions about if/how this could be applied to an alternative DNS SRV format such as DC/OS. 

The Service Locator's config isn't explained well here either, though the static config is worth noting as a valid mechanism: https://www.lagomframework.com/documentation/latest/java/ProductionOverview.html.

Adding to the confusion is the "Service Discovery" described in the Akka Management docs.

Service Location is a big enough topic that it may be worth having a page dedicated to it. 

A few things that could be included:
- Briefly what a Service Locator is and why it's necessary for Lagom applications
- Mention that static service location is an option (a pointer to the Lagom docs for this is ok)
- A description of how Reactive-App and Kubernetes solves the problem with the current instructions on how to include it.
- A concrete example show how a Lagom service call is translated into a DNS SRV look up which points to a Kubernetes Service would help understanding. This could also be useful for troubleshooting if the Service Locator doesn't work as expected. Link to the K8s Services docs as well.
- How the DNS SRV resolution would be useful if not using Kubernetes Services.

- It may also be worth articulating the different use cases for the Lagom Service APIs and Akka's Service Discovery simply because of the confusion this creates.

**Comment by TimMoore** [comment]
@ktoso right now the `reactive-lib` library includes some Lagom-specific parts, as well as some generic parts. The Lagom-specific parts are required to integrate Lagom's `ServiceLocator` API with the DNS-based service discovery mechanisms provided by Kubernetes and DC/OS.

We want to converge on a single service discovery implementation. I think this will be easier if we start by migrating the Lagom-specific parts of `reactive-lib` into the core Lagom framework. Then, the independent parts can be moved or reimplemented in Akka Discovery (in Akka Management or wherever that ends up). It's important to have a migration path for things that are already based on the Lagom `ServiceLocator`.

Specifically on the documentation side (which is what this issue is about) I think it makes more sense to have any Lagom-specific information in the Lagom documentation, rather than expanding Lagom-specific documentation in the general Lightbend Orchestration docs.

**Comment by TimMoore** [comment]
We need some more clarification of the direction we want this to move. I'll take this as something to work out and break down into new issues.

**Comment by TimMoore** [comment]
The https://www.lagomframework.com/documentation/latest/java/ProductionOverview.html page has been improved. Further improvements should target that documentation.
