### ISSUE TITLE
Document Docker image labels generated by sbt-reactive-app

### ISSUE THREAD

**Issue by chbatey** [lightbend/lightbend-orchestration-docs#63]
I missed this line in the intro "An sbt plugin, sbt-reactive-app, which inspects your projects and builds annotated Docker Images." and ended up being quite confused about how the information was being passed about until looking at the code.

I section on How it works that documents the labels would have made getting started a lot easier for me.

**Comment by TimMoore** [comment]
In addition to reference information on the available labels and their meaning, we should document how to use these labels for tooling purposes, to make it easier to write alternatives to `reactive-cli` (`rp`). For example, a tool could be written that generates Helm charts or other templates, rather than directly generating Kubernetes resource configuration.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
